"""Wire protocol between an MCP session process and the visualization hub.

The hub (``hub.py``) is a relay + session registry; each MCP server process is a
*session* that dials out to the hub (``hub_client.py``), registers, publishes
events, and answers snapshot / graph-list RPCs against its own storage. These
Pydantic models are the messages exchanged over that ``/ingest`` socket — shared
by both sides so the shapes cannot drift.

The event payloads themselves are the existing ``events.py`` contract, carried
opaquely as JSON inside ``PublishEvent`` — this module adds only the envelope
and session identity around them.
"""

from datetime import datetime, timezone
from typing import Literal

from pydantic import BaseModel, Field


def _now() -> datetime:
    return datetime.now(timezone.utc)


class SessionInfo(BaseModel):
    """Identity + current state of one MCP server process, as seen by the hub."""

    session_id: str          # uuid4, generated by the MCP process at startup
    pid: int
    backend: str             # storage.backend_name — "memory" | "surrealdb"
    active_graph: str
    started_at: datetime = Field(default_factory=_now)


# --- session → hub ---


class Register(BaseModel):
    """First message a session sends on connect; re-sent when active_graph changes."""

    type: Literal["register"] = "register"
    info: SessionInfo


class PublishEvent(BaseModel):
    """A visualization event to fan out to browsers.

    ``payload`` is a serialized ``events.py`` event, unmodified. The hub injects
    ``session_id`` into it before forwarding, so producers need not stamp it.
    """

    type: Literal["event"] = "event"
    payload: dict


class RpcResponse(BaseModel):
    """A session's answer to an ``RpcRequest`` (matched by ``request_id``)."""

    type: Literal["rpc_response"] = "rpc_response"
    request_id: str
    result: dict | None = None
    error: str | None = None


# --- hub → session ---


class RpcRequest(BaseModel):
    """A read the hub asks a session to execute in its own process.

    ``list_graphs`` takes no params; ``snapshot`` takes ``{"graph": <name>}``.
    """

    type: Literal["rpc_request"] = "rpc_request"
    request_id: str
    method: Literal["list_graphs", "snapshot"]
    params: dict = Field(default_factory=dict)


# Discriminated by the ``type`` field on parse.
SessionMessage = Register | PublishEvent | RpcResponse
HubMessage = RpcRequest
